// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface ServerPostmanEnvironment {
  id: string
  name: string
  values: Value[]
  _postman_variable_scope: string
  _postman_exported_at: string
  _postman_exported_using: string
}

export interface Value {
  key: string
  value: string
  description?: Description
  enabled: boolean
}

export interface Description {
  content: string
  type: string
}
